global class CreateRecordsWrapper {
    public String OBJNAME{get;set;}
    public String ACCNAME{get;set;}
    public String ISPARTNERACC{get;set;}
    public String LEADSOURCE{get;set;}
    public String EMAIL{get;set;}
    public String FIRSTNAME{get;set;}
    public String LASTNAME{get;set;}
    public String PHONE {get;set;}
    public String CITY {get;set;}
    public String STATE {get;set;}
    public String STREETADDRESS {get;set;}
    public String ZIPCODE {get;set;}
    public String ENTITYTYPE {get;set;}
}